chancemeuci/urls.py
from django.conf.urls import url
from . import views

app_name = 'chancemeuci'

urlpatterns = [
    # /chancemeuci/
    url(r'^$', views.index.as_view(), name='index'),
]

howtohuynh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/chancemeuci/')),
    url(r'^admin/', admin.site.urls),
    url(r'^chancemeuci/', include('chancemeuci.urls'))
]

chancemeuci/models.py
from django.db import models
from django.core.urlresolvers import reverse

ETHNICITY = (
    ('American Indian / Alaskan Native', 'American Indian / Alaskan Native'),
    ('Asian / Pacific Islander', 'Asian / Pacific Islander'),
    ('Black,  non-Hispanic', 'Black,  non-Hispanic'),
    ('Hispanic', 'Hispanic'),
    ('White,  non-Hispanic', 'White,  non-Hispanic'),
    ('Unknown / declined to state', 'Unknown / declined to state'),
    ('International student', 'International student')
)

GENDER = (
    ('Female', 'Female'),
    ('Male', 'Male'),
    ('Not stated', 'Not stated')
)

MAJOR = (
    ('Arts | Art', 'Arts | Art'),
    ('Arts | Dance', 'Arts | Dance'),
    ('Arts | Drama', 'Arts | Drama'),
    ('Arts | Music - Performance', 'Arts | Music - Performance'),
    ('Arts | Music', 'Arts | Music'),
    ('Arts | Studio Art', 'Arts | Studio Art'),
    ('Arts | Undeclared', 'Arts | Undeclared'),
    ('Biological Sciences | Biological Sciences', 'Biological Sciences | Biological Sciences'),
    ('Biological Sciences | Biology/Education', 'Biological Sciences | Biology/Education'),
    ('Biological Sciences | Ecology and Evolutionary Biology', 'Biological Sciences | Ecology and Evolutionary Biology'),
    ('Business | Business Administration', 'Business | Business Administration'),
    ('Education | Education Sciences', 'Education | Education Sciences'),
    ('Education | Undeclared', 'Education | Undeclared'),
    ('Engineering | Aerospace Engineering', 'Engineering | Aerospace Engineering'),
    ('Engineering | Biomedical Engineering', 'Engineering | Biomedical Engineering'),
    ('Engineering | Biomedical Engineering: Premed', 'Engineering | Biomedical Engineering: Premed'),
    ('Engineering | Chemical Engineering', 'Engineering | Chemical Engineering'),
    ('Engineering | Civil Engineering', 'Engineering | Civil Engineering'),
    ('Engineering | Computer Engineering', 'Engineering | Computer Engineering'),
    ('Engineering | Computer Science and Engineering', 'Engineering | Computer Science and Engineering'),
    ('Engineering | Electrical Engineering', 'Engineering | Electrical Engineering'),
    ('Engineering | Environmental Engineering', 'Engineering | Environmental Engineering'),
    ('Engineering | Materials Science Engineering', 'Engineering | Materials Science Engineering'),
    ('Engineering | Mechanical Engineering', 'Engineering | Mechanical Engineering'),
    ('Engineering | Undeclared', 'Engineering | Undeclared'),
    ('Humanities | African-American Studies', 'Humanities | African-American Studies'),
    ('Humanities | Art History', 'Humanities | Art History'),
    ('Humanities | Asian American Studies', 'Humanities | Asian American Studies'),
    ('Humanities | Chinese Language and Literature', 'Humanities | Chinese Language and Literature'),
    ('Humanities | Chinese Studies', 'Humanities | Chinese Studies'),
    ('Humanities | Classical Civilization', 'Humanities | Classical Civilization'),
    ('Humanities | Classics', 'Humanities | Classics'),
    ('Humanities | Comparative Literature', 'Humanities | Comparative Literature'),
    ('Humanities | East Asian Cultures', 'Humanities | East Asian Cultures'),
    ('Humanities | English', 'Humanities | English'),
    ('Humanities | European Studies', 'Humanities | European Studies'),
    ('Humanities | Film and Media Studies', 'Humanities | Film and Media Studies'),
    ('Humanities | French', 'Humanities | French'),
    ('Humanities | Gender and Sexuality Studies', 'Humanities | Gender and Sexuality Studies'),
    ('Humanities | German Studies', 'Humanities | German Studies'),
    ('Humanities | Global Cultures', 'Humanities | Global Cultures'),
    ('Humanities | History', 'Humanities | History'),
    ('Humanities | Japanese Lanuage and Literature', 'Humanities | Japanese Lanuage and Literature'),
    ('Humanities | Korean Literature and Culture', 'Humanities | Korean Literature and Culture'),
    ('Humanities | Latin', 'Humanities | Latin'),
    ('Humanities | Literary Journalism', 'Humanities | Literary Journalism'),
    ('Humanities | Philosophy', 'Humanities | Philosophy'),
    ('Humanities | Religious Studies', 'Humanities | Religious Studies'),
    ('Humanities | Spanish', 'Humanities | Spanish'),
    ('Humanities | Undeclared', 'Humanities | Undeclared'),
    ('Info and Computer Sci | Biomedical Computing', 'ICS | Biomedical Computing'),
    ('Info and Computer Sci | Business Information Management', 'ICS | Business Information Management'),
    ('Info and Computer Sci | Computer Game Science', 'ICS | Computer Game Science'),
    ('Info and Computer Sci | Computer Science', 'ICS | Computer Science'),
    ('Info and Computer Sci | Computer Science and Engineering', 'ICS | Computer Science and Engineering'),
    ('Info and Computer Sci | Data Science', 'ICS | Data Science'),
    ('Info and Computer Sci | Informatics', 'ICS | Informatics'),
    ('Info and Computer Sci | Information and Computer Science', 'ICS | Information and Computer Science'),
    ('Info and Computer Sci | Software Engineering', 'ICS | Software Engineering'),
    ('Info and Computer Sci | Undeclared', 'ICS | Undeclared'),
    ('Nursing Science | Nursing Science', 'Nursing Science | Nursing Science'),
    ('Pharmaceutical Sciences | Pharmaceutical Sciences', 'Pharmaceutical Sciences | Pharmaceutical Sciences'),
    ('Physical Sciences | Applied Physics', 'Physical Sciences | Applied Physics'),
    ('Physical Sciences | Chemistry', 'Physical Sciences | Chemistry'),
    ('Physical Sciences | Earth and Environmental Sciences', 'Physical Sciences | Earth and Environmental Sciences'),
    ('Physical Sciences | Earth and Environmental Studies', 'Physical Sciences | Earth and Environmental Studies'),
    ('Physical Sciences | Earth System Science', 'Physical Sciences | Earth System Science'),
    ('Physical Sciences | Environmental Science', 'Physical Sciences | Environmental Science'),
    ('Physical Sciences | Mathematics', 'Physical Sciences | Mathematics'),
    ('Physical Sciences | Physics', 'Physical Sciences | Physics'),
    ('Physical Sciences | Undeclared', 'Physical Sciences | Undeclared'),
    ('Public Health | Public Health Policy', 'Public Health | Public Health Policy'),
    ('Public Health | Public Health Sciences', 'Public Health | Public Health Sciences'),
    ('Social Ecology | Criminology, Law and Society', 'Social Ecology | Criminology, Law and Society'),
    ('Social Ecology | Psychology and Social Behavior', 'Social Ecology | Psychology and Social Behavior'),
    ('Social Ecology | Social Ecology', 'Social Ecology | Social Ecology'),
    ('Social Ecology | Undeclared', 'Social Ecology | Undeclared'),
    ('Social Ecology | Urban Studies', 'Social Ecology | Urban Studies'),
    ('Social Sciences | Anthropology', 'Social Sciences | Anthropology'),
    ('Social Sciences | Business Economics', 'Social Sciences | Business Economics'),
    ('Social Sciences | Chicano/Latino Studies', 'Social Sciences | Chicano/Latino Studies'),
    ('Social Sciences | Cognitive Sciences', 'Social Sciences | Cognitive Sciences'),
    ('Social Sciences | Economics', 'Social Sciences | Economics'),
    ('Social Sciences | International Studies', 'Social Sciences | International Studies'),
    ('Social Sciences | Linguistics', 'Social Sciences | Linguistics'),
    ('Social Sciences | Political Science', 'Social Sciences | Political Science'),
    ('Social Sciences | Psychology ', 'Social Sciences | Psychology '),
    ('Social Sciences | Quantitative Economics', 'Social Sciences | Quantitative Economics'),
    ('Social Sciences | Social Policy and Public Service', 'Social Sciences | Social Policy and Public Service'),
    ('Social Sciences | Social Science', 'Social Sciences | Social Science'),
    ('Social Sciences | Sociology', 'Social Sciences | Sociology'),
    ('Social Sciences | Undeclared', 'Social Sciences | Undeclared'),
    ('Undergrad Education | Undeclared', 'Undergrad Education | Undeclared')
)

RESIDENCY = (
    ('California resident', 'California resident'),
    ('Other U.S. citizens or permanent residents', 'Other U.S. citizens or permanent residents'),
    ('International students', 'International students')
)
HIGH_SCHOOL = (
    ('OTHER / NOT LISTED', 'OTHER / NOT LISTED'),
    ('ABRAHAM LINCOLN SR HIGH SCHOOL', 'ABRAHAM LINCOLN SR HIGH SCHOOL'),
    ('ALAMEDA HIGH SCHOOL', 'ALAMEDA HIGH SCHOOL'),
    ('ALHAMBRA HIGH SCHOOL', 'ALHAMBRA HIGH SCHOOL'),
    ('ALISO NIGUEL HIGH SCHOOL', 'ALISO NIGUEL HIGH SCHOOL'),
    ('ARCADIA SENIOR HIGH SCHOOL', 'ARCADIA SENIOR HIGH SCHOOL'),
    ('ARNOLD O BECKMAN HIGH SCHOOL', 'ARNOLD O BECKMAN HIGH SCHOOL'),
    ('ARROYO HIGH SCHOOL', 'ARROYO HIGH SCHOOL'),
    ('BISHOP MONTGOMERY HIGH SCHOOL', 'BISHOP MONTGOMERY HIGH SCHOOL'),
    ('BOLSA GRANDE HIGH SCHOOL', 'BOLSA GRANDE HIGH SCHOOL'),
    ('BREA-OLINDA HIGH SCHOOL', 'BREA-OLINDA HIGH SCHOOL'),
    ('BURBANK SR HIGH SCHOOL', 'BURBANK SR HIGH SCHOOL'),
    ('CALIFORNIA ACADEMY MATH & SCIENCE', 'CALIFORNIA ACADEMY MATH & SCIENCE'),
    ('CANYON HIGH SCHOOL', 'CANYON HIGH SCHOOL'),
    ('CAPISTRANO VALLEY HIGH SCHOOL', 'CAPISTRANO VALLEY HIGH SCHOOL'),
    ('CASTRO VALLEY HIGH SCHOOL', 'CASTRO VALLEY HIGH SCHOOL'),
    ('CENTENNIAL HIGH SCHOOL', 'CENTENNIAL HIGH SCHOOL'),
    ('CERRITOS HIGH SCHOOL', 'CERRITOS HIGH SCHOOL'),
    ('CHINO HILLS HIGH SCHOOL', 'CHINO HILLS HIGH SCHOOL'),
    ('CRESCENTA VALLEY HIGH SCHOOL', 'CRESCENTA VALLEY HIGH SCHOOL'),
    ('CYPRESS HIGH SCHOOL', 'CYPRESS HIGH SCHOOL'),
    ('DIAMOND BAR HIGH SCHOOL', 'DIAMOND BAR HIGH SCHOOL'),
    ('DIAMOND RANCH HIGH SCHOOL', 'DIAMOND RANCH HIGH SCHOOL'),
    ('DOWNEY HIGH SCHOOL', 'DOWNEY HIGH SCHOOL'),
    ('EDISON HIGH SCHOOL', 'EDISON HIGH SCHOOL'),
    ('EL CAMINO REAL SR HIGH SCHOOL', 'EL CAMINO REAL SR HIGH SCHOOL'),

chancemeuci/forms.py
from django.forms import ModelForm
from chancemeuci.models import Applicant

class ApplicantForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ApplicantForm, self).__init__(*args, **kwargs)
        self.fields['high_school'].label = "High School"
        self.fields['uc_gpa'].label = "UC GPA"
        self.fields['sat_math'].label = "SAT Math"
        self.fields['sat_verbal'].label = "SAT Verbal"
        self.fields['sat_writing'].label = "SAT Writing"
    class Meta:
        model = Applicant
        fields = '__all__'

chancemeuci/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.core.urlresolvers import reverse_lazy
from chancemeuci.models import Applicant
from chancemeuci.forms import ApplicantForm
from chancemeuci.data.ctd import csv_to_dict
from chancemeuci.data.calculator import calculate

# List to be used to convert .csv files to dict
appliedList = ['applied', 'admitted', 'enrolled', 'selectivity_rate', 'yield_rate', 'gpa', 'verbal', 'math',
               'writing']
appliedList2 = ['applied', 'admitted', 'enrolled', 'selectivity_rate', 'yield_rate']
highschoolList = ['admitted']

school = csv_to_dict('chancemeuci/data/csv_files/school.csv', appliedList)
major = csv_to_dict('chancemeuci/data/csv_files/major.csv', appliedList)
gender = csv_to_dict('chancemeuci/data/csv_files/gender.csv', appliedList)
high_school = csv_to_dict('chancemeuci/data/csv_files/high_school.csv', highschoolList)
residency = csv_to_dict('chancemeuci/data/csv_files/residency.csv', appliedList[:5])
ethnicity = csv_to_dict('chancemeuci/data/csv_files/ethnicity.csv', appliedList)
school_gender = csv_to_dict('chancemeuci/data/csv_files/school_gender.csv', appliedList)
school_ethnicity = csv_to_dict('chancemeuci/data/csv_files/school_ethnicity.csv', appliedList)
uc_gpa = csv_to_dict('chancemeuci/data/csv_files/gpa.csv', appliedList2)
sat_verbal = csv_to_dict('chancemeuci/data/csv_files/verbal.csv', appliedList2)
sat_math = csv_to_dict('chancemeuci/data/csv_files/math.csv', appliedList2)
sat_writing = csv_to_dict('chancemeuci/data/csv_files/writing.csv', appliedList2)


class index(CreateView):
    template_name = 'chancemeuci/applicant_form.html'
    model = Applicant
    fields = ['major', 'gender', 'ethnicity', 'residency', 'high_school', 'uc_gpa', 'sat_math', 'sat_verbal',
              'sat_writing']

    def get(self, request):
        form = ApplicantForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ApplicantForm(request.POST or None)
        if form.is_valid():
            form_data = form.cleaned_data
            form.save()
        l = lowWeight(form_data)
        h = highWeight(form_data)
        data = l
        data.extend(h)
        cl = calculate(l)
        ch = calculate(h)
        r = cl[0]
        r.extend(ch[0])
        chances = "{0:.2f}%".format(((ch[1] * 2) + cl[1])/3)
        r.sort()
        chance_string = "Your overall chance is {}, but can range anywhere from {}% to {}%.".format(chances, r[0], r[-1])
        hs = highSchool(form_data)
        args = {'form': form, 'form_data': form_data, 'min': r[0], 'max': r[-1], 'chances': chance_string, 'ld': l, 'hs': hs}
        return render(request, self.template_name, args)


# Returns the average acceptance rate of factors that are weighed on a lower scale
def lowWeight(d: dict) -> float:
    low_weight = []
    x = d['major'].split(" | ")[0]
    y = d['major'].split(" | ")[1]

    low_weight.append((('School', x), school[x]))
    low_weight.append((('Major', y), major[x][y]))
    low_weight.append((('Gender', d['gender']), gender[d['gender']]))
    low_weight.append((('Ethnicity', d['ethnicity']), ethnicity[d['ethnicity']]))
    low_weight.append((('School & Gender', x + " & " + d['gender']), school_gender[x][d['gender']]))
    low_weight.append((('School & Ethnicity', x + " & " + d['ethnicity']), school_ethnicity[x][d['ethnicity']]))
    low_weight.append((('Residency', d['residency']), residency[d['residency']]))
    return low_weight

# Returns the average acceptance rate of factors that are weighed on a higher scale
def highWeight(d: dict) -> float:
    high_weight = []
    high_weight.append((('UC GPA', d['uc_gpa']), uc_gpa[d['uc_gpa']]))
    high_weight.append((('SAT Verbal', d['sat_verbal']), sat_verbal[d['sat_verbal']]))
    high_weight.append((('SAT Math', d['sat_math']), sat_math[d['sat_math']]))
    high_weight.append((('SAT Writing', d['sat_writing']), sat_writing[d['sat_writing']]))
    return high_weight

# Returns a string containing information about the amount of students enrolled from a certain high school
def highSchool(d: dict) -> str:
    if d['high_school'] != 'OTHER / NOT LISTED':
        string = "In 2016, {} people from {} enrolled at UC Irvine.".format(high_school[d['high_school']]['admitted'], d['high_school'].title())
    else:
        string = ''
    return string

chancemeuci/templates/chancemeuci/applicant_form.html
{% extends 'chancemeuci/base.html' %}
{% block body %}
    <div class = "container-fluid">
        <div class = "row">
            <div class="col-sm-4 col-sm-offset-0">
              <div class="panel panel-default">
                    <div class = "panel-body">
                        <form class = "form-horizontal" action = "" method = "post" enctype = "multipart/form-data">
                            {% csrf_token %}
                            {% include 'chancemeuci/form-template.html' %}
                            <div class = "form-group">
                                <div class = "col-sm-offset-6 col-sm-6">
                                    <button type = "submit" class = "btn btn-success"> Chance Me! </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class = "col-sm-8">
                <div  class="panel panel-default">
                    <h3>
                        <p class="text-center">{{ chances }}</p>
                    </h3>
                    <h4>
                        <p class="text-center">{{ hs }}</p><br/>
                    </h4>
                    {% include 'chancemeuci/table-template.html' %}
                </div>
            </div>
            <div>
                <p class="text-center"> Disclaimer - Other than as an undergraduate student, I am not affiliated with the University of California, Irvine.
                                        This calculator cannot predict your exact chances of admission into UC Irvine, but it will provide an estimate and
                                        range based on 2016 data.</p>
                <p class="text-center"> © Kenny Huynh 2017 </p>
                <p class="text-center"> www.howtohuynh.com </p>
            </div>
        </div>
    </div>
<style>



</style>

{% endblock %}

chancemeuci/templates/chancemeuci/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset = 'UTF-8'>
    <title>{% block title %} Chance Me! UC Irvine Edition {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href = "https://fonts.googleapis.com/css?family=Cinzel" rel = "stylesheet" type = "text/css">
    <link rel = "stylesheet" type = "text/css" href = "{% static 'chancemeuci/../../../static/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class = "navbar navbar-inverse">
    <div class = "container-fluid">
        <!-- Header -->
        <div class = "navbar-header">
            <button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar">
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
            </button>
            <a class = "navbar-brand" href = "{% url 'chancemeuci:index' %}"> Chance Me UCI </a>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

chancemeuci/templates/chancemeuci/form-template.html
{% for field in form %}
    <div class = "form-group">
        <div class = "col-sm-offset-0 col-sm-0">
            <span class = "text-danger small"> {{ field.errors }}</span>
        </div>
        <label class = "control-label col-sm-offset-1 col-sm-0"> {{ field.label_tag }}</label>
        <div class = "col-sm-offset-1 col-sm-0"> {{ field }}</div>
    </div>
{% endfor %}

chancemeuci/templates/chancemeuci/index.html
{% extends 'chancemeuci/base.html' %}

{% block body %}
{% endblock %}

chancemeuci/templates/chancemeuci/table-template.html
<table class="table table-sm table-hover">
  <thead>
    <tr>
        <th>Description</th>
        <th>Your Stats</th>
        <th>Applied</th>
        <th>Admitted</th>
        <th>Enrolled</th>
        <th>Selectivity</th>
        <th>Yield</th>
        <th>GPA</th>
        <th>Verbal</th>
        <th>Math</th>
        <th>Writing</th>
    </tr>
  </thead>
  <tbody>
        {% for field in ld %}
            <tr>
            {% for x in field %}
                {% if x|length == 2 %}
                    {% for value in x %}
                        <td> {{ value }}</td>
                    {% endfor%}
                {% elif x|length == 5 %}
                    {% for key, value in x.items %}
                        <td> {{ value }}</td>
                        {% endfor %}
                    <td> {{ "N/A" }}</td>
                    <td> {{ "N/A" }}</td>
                    <td> {{ "N/A" }}</td>
                    <td> {{ "N/A" }}</td>
                {% else %}
                    {% for key, value in x.items %}
                        <td> {{ value }}</td>
                    {% endfor %}
                {% endif %}
            {% endfor %}
            </tr>
        {% endfor %}
  </tbody>
</table>
